name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
		- name: Install dependencies 1 
			run: npm ci

		- name: Run lint 1
			run: npm run style:all